///////////////////////////////////////////////////////////////////////////////
// ExampleServices.h

#pragma once

#include "TcServices.h"

const ULONG DrvID_Example = 0x3F000000;
#define SRVNAME_EXAMPLE "Example"

///<AutoGeneratedContent id="ClassIDs">
const CTCID CID_ExampleCAddInputToOutput = {0x1b74e3e2,0x84f6,0x40fa,{0x8e,0x6a,0x3c,0xfb,0x34,0xfe,0x84,0xb8}};
///</AutoGeneratedContent>

///<AutoGeneratedContent id="ParameterIDs">
const PTCID PID_AddInputToOutputDiff = 0x00000001;
///</AutoGeneratedContent>

///<AutoGeneratedContent id="DataTypes">
typedef struct _AddInputToOutputInputs
{
	ULONG Value;
} AddInputToOutputInputs, *PAddInputToOutputInputs;

typedef struct _AddInputToOutputOutputs
{
	ULONG Value;
} AddInputToOutputOutputs, *PAddInputToOutputOutputs;

///</AutoGeneratedContent>



///<AutoGeneratedContent id="DataAreaIDs">
#define ADI_AddInputToOutputInputs 0
#define ADI_AddInputToOutputOutputs 1
///</AutoGeneratedContent>

///<AutoGeneratedContent id="InterfaceIDs">
///</AutoGeneratedContent>

///<AutoGeneratedContent id="EventClasses">
///</AutoGeneratedContent>
