///////////////////////////////////////////////////////////////////////////////
// ExampleClassFactory.cpp
#include "TcPch.h"
#pragma hdrstop

#include "ExampleClassFactory.h"
#include "ExampleServices.h"
#include "ExampleVersion.h"
#include "AddInputToOutput.h"

BEGIN_CLASS_MAP(CExampleClassFactory)
///<AutoGeneratedContent id="ClassMap">
	CLASS_ENTRY_LIB(VID_Example, CID_ExampleCAddInputToOutput, SRVNAME_EXAMPLE "!CAddInputToOutput", CAddInputToOutput)
///</AutoGeneratedContent>
END_CLASS_MAP()

CExampleClassFactory::CExampleClassFactory() : CObjClassFactory()
{
	TcDbgUnitSetImageName(TCDBG_UNIT_IMAGE_NAME_TMX(SRVNAME_EXAMPLE));
#if defined(TCDBG_UNIT_VERSION)
	TcDbgUnitSetVersion(TCDBG_UNIT_VERSION(Example));
#endif //defined(TCDBG_UNIT_VERSION)
}

