///////////////////////////////////////////////////////////////////////////////
// tinyxml2Interfaces.h

#pragma once

#include "TcInterfaces.h"
#include "TcIoInterfaces.h"
#include "tinyxml2Services.h"

///<AutoGeneratedContent id="Interfaces">
///</AutoGeneratedContent>
