///////////////////////////////////////////////////////////////////////////////
// tinyxml2Services.h

#pragma once

#include "TcServices.h"

const ULONG DrvID_tinyxml2 = 0x3F000000;
#define SRVNAME_TINYXML2 "tinyxml2"

///<AutoGeneratedContent id="ClassIDs">
///</AutoGeneratedContent>

///<AutoGeneratedContent id="ParameterIDs">
///</AutoGeneratedContent>

///<AutoGeneratedContent id="DataTypes">
///</AutoGeneratedContent>


